version: '3.2'

services:
  database:
    image: mysql:5.7
    environment:
      TZ: Europe/Rome
      MYSQL_ROOT_PASSWORD: restchain
      MYSQL_DATABASE: restchain
      MYSQL_USER: restchain
      MYSQL_PASSWORD: restchain
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - 3307:3306
    expose:
      - 3307

  ipfs-service:
    container_name: ipfs-service
    image: restchain/restchain-ipfs-service:0.2
    ports:
      - 4001:4001 # ipfs swarm - expose if needed/wanted
      - 127.0.0.1:5001:5001 # ipfs api - expose if needed/wanted
      - 127.0.0.1:8080:8080 # ipfs gateway - expose if needed/wanted
    volumes:
      - ./data/ipfs:/data/ipfs
      - ./data/ipfs-staging:/staging

  backend:
    image: restchain/restchain-service:1.0.0
    depends_on:
      - database
      - ipfs-service
    environment:
      spring.datasource.url: jdbc:mysql://database:3306/restchain?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      spring.datasource.username: restchain
      spring.datasource.password: restchain
      spring.jpa.database: mysql
      solidity.gas.price: 2500000015
      solidity.gas.limit: 20000000
      solidity.node.url: https://rpc-mumbai.maticvigil.com/
      solidity.node.chainId: 80001
      solidity.account.admin: '0xcC88B43de8E861e01F17127a0F59BbfD17c1e699'
      solidity.admin.keyfile: 'afc9b7e192122f7b47e113b55b55be58fff15343cfdf126f9abcd192d275c2a3'
      web3j.client-address: https://rpc-mumbai.maticvigil.com/
      solidity.pragma.solidity-version: ^0.5.17
      springdoc.api-docs.path: /api-docs
    volumes:
    - ./upload-dir:/app/upload-dir
    - ./solidity-dir:/app/solidity-dir
    ports:
      - 8085:8085
    #expose:
      - 8085
    restart: on-failure

  frontend:
    image: restchain/restchain-web:0.6
    depends_on:
      - backend
    ports:
      - 80:80
    expose:
      - 80
    restart: on-failure

  mediator1:
    image: restchain/restchain-web-mediator:0.5
    depends_on:
      - backend
    ports:
      - 81:80
    expose:
      - 81

  mediator2:
    image: restchain/restchain-web-mediator:0.5
    depends_on:
      - backend
    ports:
      - 82:80
    expose:
      - 82

  mediator3:
    image: restchain/restchain-web-mediator:0.5
    depends_on:
      - backend
    ports:
      - 83:80
    expose:
      - 83    
